
extensions: {}

receivers:        
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

connectors: {}

processors:

  batch/logs:
    send_batch_max_size: 1000
    send_batch_size: 200
    timeout: 10

exporters:
  debug/development:
    verbosity: detailed
    use_internal_logger: false
  
  nop:

service:
  telemetry:
    logs:
      level: "info"
    metrics:
      level: detailed
      address: 0.0.0.0:8888
  extensions: []
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug/development]

    traces:
      receivers: [otlp]
      processors: []
      exporters: [debug/development]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug/development]