
extensions: {}

receivers:        
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

connectors: {}

processors:

  batch/logs:
    send_batch_max_size: 1000
    send_batch_size: 200
    timeout: 10

exporters:
  debug/development:
    verbosity: detailed
    use_internal_logger: false
  
  nop:

  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    timeout: 5s
    add_metric_suffixes: false
    remote_write_queue:
      enabled: true
      num_consumers: 10
      queue_size: 10000
    resource_to_telemetry_conversion:
      enabled: false

service:
  telemetry:
    logs:
      level: "info"
    metrics:
      level: detailed
      address: 0.0.0.0:8888
  extensions: []
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheusremotewrite]