services:
  app:
    image: jcabrera9409/aws-test:1.0
    container_name: aws-test-container
    depends_on:
      - db
    environment:
      - HOST_BD=db
      - PORT_BD=3306
      - NAME_BD=testdb
      - USER_BD=root
      - PASSWORD_BD=root
    ports:
      - "8080:8080"
    restart: always

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

  prometheus:
    image: prom/prometheus:v3.2.1
    ports:
      - "9090:9090"
    volumes: 
      - ./prometheus-docker/:/etc/prometheus/
      - ./prometheus-data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-remote-write-receiver'

volumes:
  mysql_data: