spring:
  application:
    name: colegio

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${HOST_BD:localhost}:${PORT_BD:3306}/${NAME_BD:testdb}
    username: ${USER_BD:root}
    password: ${PASSWORD_BD:root}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false
  level:
    org.springframework.web: INFO
    com.surrender.colegio: INFO

