name: Deployment Pipeline

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Download Maven dependencies
        run: mvn dependency:go-offline
      - name: Build with Maven
        run: mvn -B package --file pom.xml